name: Generate Pac-Man contribution graph

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم
  workflow_dispatch:     # تشغيل يدوي

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@v3
        with:
          github_user_name: TP0351578
          outputs: |
            ./dist/pacman-contribution-graph.svg
            ./dist/pacman-contribution-graph-dark.svg
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
